name: zooplankton-tools
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.2
  - matplotlib==3.0.1
  - numpy==1.15.4
  - pandas==0.23.4
  - xlrd==1.2.0
  - scipy==1.4.1
  - statsmodels==0.11.1